steps:
# TypeScriptをビルド
- name: 'node:20-alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    npm ci
    npm run build
    
# 最適化版Dockerイメージをビルド
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.optimized', '-t', 'gcr.io/azuki-generator/azuki-backend', '.']
  
images:
- 'gcr.io/azuki-generator/azuki-backend'